version: "3.5"

services:
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.5.3
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/bazarr:/config
      - /mnt/wd5tb/media/movies:/movies
      - /mnt/wd5tb/media/tv:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "glance.name=Bazarr"
      - "glance.icon=si:subtitleedit"
      - "glance.url=http://bazarr.home.local/"
      - "glance.description=Subtitle Manager"
