version: "3.8"

services:
  netdata:
    image: netdata/netdata:v2.8
    container_name: netdata
    hostname: netdata # appears in the Netdata UI
    restart: unless-stopped
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      # Host monitoring mounts:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    networks:
      lan:
        ipv4_address: 172.19.0.26
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.rule=Host(`netdata.home.local`)"
      - "glance.name=Netdata"
      - "glance.icon=si:netdata"
      - "glance.url=http://netdata.home.local/"
      - "glance.description=Monitoring"

volumes:
  netdata_config:
  netdata_lib:
  netdata_cache:
