version: "3.5"

services:
  glance:
    container_name: Glance
    image: glanceapp/glance:v0.8.4
    volumes:
      - /srv/docker/glance:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8020:8080
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 172.19.0.25
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`glance.home.local`)"
      - glance.name=Glance
      - glance.icon=si:homepage
      - glance.url=http://glance.home.local/
      - glance.description=Homelab Homepage

networks:
  lan:
    external: true
